### ISSUE TITLE
Better exception messages please

### ISSUE THREAD

**Issue by asger-weirsoee** [droolsassert/droolsassert#8]
This is a feature request for better exception messages.

I have the following testcase
```java
@Test
@TestRules(expected = "Check_DyrAlder")
public void testInt() {
    InputObject inputObject = getInputObject(2002, 2003,
            new DroolsObject() {{
                put("AnimalId", 1);
                put("DyrAlder", 1);
                put("Weight", 100f);
                put("HandyrAlder", 30);
                put("RequestYear", 2021);
                put("Identification", 1);
            }}

    );
    drools.insertAndFire(inputObject.getInput());
}
```

My class looks like this;
```java
@DroolsSession(resources = {
        "classpath*:/src/test/resources/rules/rules.drl"},
        builderProperties = "drools.dump.dir = target/dump",
        logResources = true)
```
And I receive the following exception:
```
java.lang.NullPointerException
	at org.droolsassert.DroolsAssert.insertAndFire(DroolsAssert.java:787)
	at org.droolsassert.DroolsAssert.insertAndFire(DroolsAssert.java:765)
	at utils.KieServerAccessorTest.testInt(KieServerAccessorTest.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

```

I would love to receive something besides a a nullpointer exception, like what are we complaining about? I know that I've got the testcase in my rules.drl. So is it the path that is wrong, is it the dump dir, or something completely different?

Thanks in advance!

**Comment by droolsassert** [comment]
Hi there,

Added better exception message when null object is inserted, could you please check v.3.0.8

Also in your example `"classpath*:/src/test/resources/rules/rules.drl"` is wrong. Usually `/src/test/resources` directory is added to the classpath, thus you should look for your drl like `"classpath*:/rules/rules.drl"` or `"classpath*:rules/rules.drl"` or `rules/rules.drl` (because classpath is the default lookup location, on documentation page it is used explicitly to emphasize other options).

Regards
