### ISSUE TITLE
Issue when running with Junit4

### ISSUE THREAD

**Issue by jlayak** [droolsassert/droolsassert#9]
##Test class

```
@DroolsSession(resources = "classpath:com/ebay/rules/AutoEscalate.drl")
public class AutoEscalateTest {

  @Rule
  public DroolsAssert drools = new DroolsAssert();

  @Test
  @TestRules(expected = "atomic int rule")
  public void testInt() {
    drools.insertAndFire(new AtomicInteger());
    assertEquals(1, drools.getObject(AtomicInteger.class).get());
  }
```
Test ignored.

java.lang.ExceptionInInitializerError
	at org.kie.api.internal.utils.ServiceRegistry.getInstance(ServiceRegistry.java:41)
	at org.kie.api.internal.utils.ServiceRegistry.getService(ServiceRegistry.java:37)
	at org.kie.api.KieServices$Factory$LazyHolder.<clinit>(KieServices.java:358)
	at org.kie.api.KieServices$Factory.get(KieServices.java:365)
	at org.kie.internal.utils.KieHelper.<init>(KieHelper.java:44)
	at org.droolsassert.DroolsAssert.kieBase(DroolsAssert.java:235)
	at org.droolsassert.DroolsAssert.newSession(DroolsAssert.java:224)
	at org.droolsassert.DroolsAssert.init(DroolsAssert.java:201)
	at org.droolsassert.DroolsAssert.apply(DroolsAssert.java:828)
	at org.junit.rules.RunRules.applyAll(RunRules.java:26)
	at org.junit.rules.RunRules.<init>(RunRules.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.withTestRules(BlockJUnit4ClassRunner.java:400)
	at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:356)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:278)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: Unable to find any instance of classes: [org.drools.wiring.dynamic.DynamicServiceRegistrySupplier, org.kie.kogito.wiring.statics.KogitoStaticServiceRegistrySupplier, org.drools.wiring.statics.StaticServiceRegistrySupplier]
	at org.kie.api.internal.utils.ServiceUtil.lambda$instanceFromNames$0(ServiceUtil.java:31)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.kie.api.internal.utils.ServiceUtil.instanceFromNames(ServiceUtil.java:31)
	at org.kie.api.internal.utils.ServiceRegistry$Impl.getServiceRegistry(ServiceRegistry.java:89)
	at org.kie.api.internal.utils.ServiceRegistry$ServiceRegistryHolder.<clinit>(ServiceRegistry.java:49)
	... 27 more

**Comment by madamovych** [comment]
Does adding [drools-wiring-static](https://search.maven.org/artifact/org.drools/drools-wiring-static) fix the problem?

**Comment by jlayak** [comment]
I added the maven dependency and see below issue now 

```
java.lang.ExceptionInInitializerError
	at org.drools.dynamic.DynamicServiceRegistrySupplier.get(DynamicServiceRegistrySupplier.java:32)
	at org.drools.dynamic.DynamicServiceRegistrySupplier.get(DynamicServiceRegistrySupplier.java:23)
	at org.kie.api.internal.utils.ServiceRegistry$Impl.getServiceRegistry(ServiceRegistry.java:90)
	at org.kie.api.internal.utils.ServiceRegistry$ServiceRegistryHolder.<clinit>(ServiceRegistry.java:49)
	at org.kie.api.internal.utils.ServiceRegistry.getInstance(ServiceRegistry.java:41)
	at org.kie.api.internal.utils.ServiceRegistry.getService(ServiceRegistry.java:37)
	at org.kie.api.KieServices$Factory$LazyHolder.<clinit>(KieServices.java:358)
	at org.kie.api.KieServices$Factory.get(KieServices.java:365)
	at org.kie.internal.utils.KieHelper.<init>(KieHelper.java:44)
	at org.droolsassert.DroolsAssert.kieBase(DroolsAssert.java:235)
	at org.droolsassert.DroolsAssert.newSession(DroolsAssert.java:224)
	at org.droolsassert.DroolsAssert.init(DroolsAssert.java:201)
	at org.droolsassert.DroolsAssert.apply(DroolsAssert.java:828)
	at org.junit.rules.RunRules.applyAll(RunRules.java:26)
	at org.junit.rules.RunRules.<init>(RunRules.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.withTestRules(BlockJUnit4ClassRunner.java:400)
	at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:356)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:278)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: Unable to build kie service url = jar:file:/Users/jlayak/.m2/raptor2/org/drools/drools-mvel/7.73.0.Final/drools-mvel-7.73.0.Final.jar!/META-INF/kie/drools-mvel/kie.conf
	at org.kie.api.internal.utils.ServiceDiscoveryImpl.registerConfs(ServiceDiscoveryImpl.java:127)
	at org.kie.api.internal.utils.ServiceDiscoveryImpl.lambda$getServices$1(ServiceDiscoveryImpl.java:105)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.kie.api.internal.utils.ServiceDiscoveryImpl.getServices(ServiceDiscoveryImpl.java:103)
	at org.kie.api.internal.utils.ServiceRegistry$Impl.<init>(ServiceRegistry.java:62)
	at org.drools.dynamic.DynamicServiceRegistrySupplier$LazyHolder.<clinit>(DynamicServiceRegistrySupplier.java:27)
	... 31 more
Caused by: java.lang.RuntimeException: Cannot create instance of class: org.drools.mvel.MVELCoreComponentsBuilder
	at org.kie.api.internal.utils.ServiceDiscoveryImpl.newInstance(ServiceDiscoveryImpl.java:164)
	at org.kie.api.internal.utils.ServiceDiscoveryImpl.processKieService(ServiceDiscoveryImpl.java:146)
	at org.kie.api.internal.utils.ServiceDiscoveryImpl.registerConfs(ServiceDiscoveryImpl.java:123)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: org/drools/core/base/CoreComponentsBuilder
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:365)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.kie.api.internal.utils.ServiceDiscoveryImpl.newInstance(ServiceDiscoveryImpl.java:162)
	... 38 more
Caused by: java.lang.ClassNotFoundException: org.drools.core.base.CoreComponentsBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:365)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 53 more
```

. I am using Java 8 for my application and added 
```
     <dependency>
            <groupId>org.droolsassert</groupId>
            <artifactId>droolsassert</artifactId>
            <version>2.5.10</version>
        </dependency>
```

**Comment by madamovych** [comment]
this is not enough, you should add all dependencies your application work with.
ClassNotFoundException: org.drools.core.base.CoreComponentsBuilder says that class is not in your classpath.
Please add respective dependency

**Comment by jlayak** [comment]
Works fine now , thanks for replying.
